### ISSUE TITLE
I got this error when run the code

### ISSUE THREAD

**Issue by Moohanad** [ThomHurks/dblp-to-csv#1]
C:\Users\Mooh\pychpr\dblp>python dblp.py dblp.xml dblp.dtd output.csv
Start!
Reading elements from DTD file...
Finding unique attributes for all elements...
Opening output files...
Parsing XML and writing to CSV files...
Traceback (most recent call last):
  File "dblp.py", line 400, in <module>
    main()
  File "dblp.py", line 378, in main
    relations, unique_id = parse_xml(xml_file, elements, output_files, args.relations)
  File "dblp.py", line 167, in parse_xml
    set_relation_values(relations, data, relation_attributes, unique_id)
  File "dblp.py", line 195, in set_relation_values
    if column_name in relation_attributes:
TypeError: argument of type 'NoneType' is not iterable

**Comment by umerpervaiz12** [comment]
i am getting this same issue kindly resolve it

**Comment by ThomHurks** [comment]
Apologies, took a while for me to pick up this project again, but I'm updating it against the latest DBLP now and testing it more properly. Fixed in the latest revision.
