### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by umerpervaiz12** [ThomHurks/dblp-to-csv#2]
Start!
Reading elements from DTD file...
Finding unique attributes for all elements...
Opening output files...
Parsing XML and writing to CSV files...
Traceback (most recent call last):
File "myscript.py", line 400, in 
main()
File "myscript.py", line 378, in main
relations, unique_id = parse_xml(xml_file, elements, output_files, args.relations)
File "myscript.py", line 167, in parse_xml
set_relation_values(relations, data, relation_attributes, unique_id)
File "myscript.py", line 195, in set_relation_values
if column_name in relation_attributes:
TypeError: argument of type 'NoneType' is not iterable

kindly resolve this issue

**Comment by ThomHurks** [comment]
Apologies, took a while for me to pick up this project again, but I'm updating it against the latest DBLP now and testing it more properly. Fixed in the latest revision.
