### ISSUE TITLE
Got this error while running the script

### ISSUE THREAD

**Issue by casaar97** [ThomHurks/dblp-to-csv#3]
Traceback (most recent call last):
  File "./XMLToCSV.py", line 412, in <module>
    main()
  File "./XMLToCSV.py", line 387, in main
    relation_attributes, annotate=True)
  File "./XMLToCSV.py", line 172, in parse_xml
    set_type_information(element_types, current_tag, key, value)
  File "./XMLToCSV.py", line 242, in set_type_information
    types.add(get_type(value))
  File "./XMLToCSV.py", line 263, in get_type
    date.fromisoformat(string_value)
AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'

**I tried with dblp-2019-01-01.xml and dblp-2017-08-29.dtd**

**Comment by ThomHurks** [comment]
@casaar97 ```fromisoformat``` is new in Python 3.7, do you have that installed?

**Comment by casaar97** [comment]
I have just installed Python 3.7, I'm new at this so what I did was just:

1. Download your respository as a zip and unzip it
2. Place the dblp.xml and dblp.dtd on the same folder
3. Installed Python 3.7 and run the commands that you have as an example on your repository
![Captura de pantalla de 2019-04-04 21-25-26](https://user-images.githubusercontent.com/22341152/55582684-f382c580-56d4-11e9-858a-09b26da0cddf.png)
![Captura de pantalla de 2019-04-04 21-26-10](https://user-images.githubusercontent.com/22341152/55582686-f382c580-56d4-11e9-89e9-79d858fd0112.png)

The problem persist, the error is the same after installing Python 3.7.
Maybe I'm doing something wrong, Is that what I was supposed to do? :)
Thanks for helping!

**Comment by ThomHurks** [comment]
What version do you see when you do ```python3 --version```?

**Comment by casaar97** [comment]
I installed python 3.7 but was using 3.6 by default, so I have now got to change it. :)
The error is solve, but now have problems with lmxl:
I've been trying to install lxml too but couldn't, nothing worked:
![Captura de pantalla de 2019-04-04 23-32-36](https://user-images.githubusercontent.com/22341152/55590927-259e2280-56e9-11e9-87ec-b0589ce867b3.png)

**Comment by ThomHurks** [comment]
Can you try ```pip3 install lxml```?

**Comment by casaar97** [comment]
I finally got to install it ( Had some problems with the OS, now fixed).
Everything works perfectly right now! :)
Thanks a lot for your help, your script is really useful and I wanted to import the data in neo4j so its perfect for me.

**Comment by ThomHurks** [comment]
Cool! If there's anything I can do then let me know.
