### ISSUE TITLE
character encoding

### ISSUE THREAD

**Issue by geojochen** [ThomHurks/dblp-to-csv#4]
I get through the following stages of the script:
   Start!
   Reading elements from DTD file...
   Finding unique attributes for all elements...
   Opening output files...
   Parsing XML and writing to CSV files...

Then, it throws the following error:

   Python\Python37\Lib\encodings\cp1252.py, line 19, in encode return 
   codecs.charmap_encode(input,self.errors,encoding_table)[0] unicodeEncodeError: 'charmap' 
   codec can't encode character '\u221e' in position 186: character maps to <undefined>

The three optional 8-bit hex characters for this infinity sign are already taken up by special (accent) characters in the de/encoding table. Should I change the table in that (Python 3.7) system file or what should I do?

Cheers,
      Jochen

**Comment by stefano-baruffaldi** [comment]
I think I solved this by imposing the encoding: open(..., 'w', encoding='utf8')
note: the csv file may show up with weird characters in excel, if the default encoding is not utf8

> I get through the following stages of the script:
> Start!
> Reading elements from DTD file...
> Finding unique attributes for all elements...
> Opening output files...
> Parsing XML and writing to CSV files...
> 
> Then, it throws the following error:
> 
> Python\Python37\Lib\encodings\cp1252.py, line 19, in encode return
> codecs.charmap_encode(input,self.errors,encoding_table)[0] unicodeEncodeError: 'charmap'
> codec can't encode character '\u221e' in position 186: character maps to
> 
> The three optional 8-bit hex characters for this infinity sign are already taken up by special (accent) characters in the de/encoding table. Should I change the table in that (Python 3.7) system file or what should I do?
> 
> Cheers,
> Jochen

**Comment by ThomHurks** [comment]
If your default system locale is not UTF-8, then you can just run Python3.7+ with ```-X utf8``` to coerce UTF-8 encoding, no code changes needed. However, since this script does not seem to work when running on systems that do not default to UTF-8, I decided to just force writing as UTF-8 always, so basically @ste210's fix. Thanks!

**Comment by wasimali356** [comment]
Can you please help me fixing this


![error](https://user-images.githubusercontent.com/75903422/101988794-cc5c0400-3cbd-11eb-880b-5237dce36952.JPG)
